### ISSUE TITLE
Consolidated dashboard

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitor#21]
Includes:
Rig hashrate gauge (single and dual mining)
Pool hashrate gauge (single and dual mining)
Net hashrate gauge (single and dual mining)
hashrate per rig graph (single and dual mining)
Shares per rig graph (single and dual mining)
Payouts graph
Top 10 GPus with inc. shares (sing and dual mining)
Top 10 GPUs with highest temp, fan
Currency graph
Profitability graph
Power consumption graph
Table with current/max power consumption, current/target hashrate, mining time

@wishbone1138, any other ideas?

**Comment by wishbone1138** [comment]
One thing I like to track over time is hash rate per GPU.  You're already storing that information.  It's helpful to watch when one of your GPUs starts to fail or has issues.  It's also extremely useful for tuning.

Pool switches could be interesting?

I got my smart things working (with influx and writing to the database instead of pulling from the API, more on that if you're interested).  For power it might be nice to see cost per hour, per day, per month, etc.  It can get complicated for those of us who have rates that change during the day, but I just use an average rate to get an idea.  This would also be necessary for any profit graphs if you wanted to take electricity cost into that.

I'm still building my dashboards, so I'll let you know what I come up with.

**Comment by rodneymo** [comment]
@wishbone1138 can we close this one? I have created a page in the wiki to capture all the report/panels needed?

**Comment by wishbone1138** [comment]
Sounds good!

**Comment by rodneymo** [comment]
Closed. Panel requirements captured in wiki
