### ISSUE TITLE
Scan Rig in network.

### ISSUE THREAD

**Issue by namlogan** [rodneymo/rig-monitor#25]
Hello,

Thank for your great work. Can rig-monitor scan whole rigs in network or manual input to rig-minitor.conf ?
#RIG NAME, IP, PLUG IP, INSTALLED GPUS, TARGET HASHRATE, TARGET HASHRATE (2nd COIN), TARGET TEMP, MAX POWER

Can you explain me about target hashrate/ target temp? I think it's collected via Claymore already.

Regards,
NamBui

**Comment by rodneymo** [comment]
Scanning is currently not supported, but that's a good idea. I'll create an feature request for it.

TARGET HASHRATES and TARGET POWER, TEMP is a reference point so that you can use gauges to quickly access operational status of those params e.g.
if RIG A has a hashrate of 180 Mh/s at optimal conditions then you can use that reference point to create a gauge/dial panel that shows the percentage of  the rig hashrate vs the actual (let's say 150 Mh/s). In such case the gauge would show  83.33% (150/180) so that you'd know something is off. Same principle for POWER and TEMP. 
 
BTW, you don't need to use them you can just leave them empty if you wish.

**Comment by namlogan** [comment]
Thanks for your clarify!
Great work again.
Regards,
NamBui
